- hosts: localhost
  vars_files:
    - var.yml
  tasks:
    - name: geting the system ip_address
      debug:
        var: ansible_default_ipv4['address']
    - name: checking memory space
      debug:
        var: ansible_memfree_mb

    - name: msg from debug
      debug:
        msg: " Hai this is Ansible {{ CreaterName }}
               We Creating Sample Web Page"
    - name: package
      package:
        name: " {{ packageName }}"
        state: present
      when: "{{ CanCreate }}"

    - name: creating new config file
      file:
        state: directory
        path: " {{webpagedir}}"

    - name: copying
      copy:
        src: "index.html"
        dest: "{{webpagedir}}"
    - name: changing config file settings
      copy:
        dest: "/etc/httpd/conf.d/my.conf"
        content: "documentroot {{webpagedir}}"
    - name: service starting
      service:
        name: "httpd"
        state: reloaded
        enabled: true
