- hosts: localhost
  tasks:
    - name: package installing
      package: " name=httpd state=present"
    - name: file copyin
      copy: "src=index.html dest=/var/www/html "
    - name: service starting
      service: " name=httpd state=started"
